//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference2
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="StudentList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Student")]
    public class StudentList : System.Collections.Generic.List<ServiceReference2.Student>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Student : ServiceReference2.People
    {
        
        private ServiceReference2.LessonList lessonListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.LessonList lessonList
        {
            get
            {
                return this.lessonListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.lessonListField, value) != true))
                {
                    this.lessonListField = value;
                    this.RaisePropertyChanged("lessonList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference2.City))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference2.Lesson))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference2.People))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference2.Lecturer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference2.Student))]
    public partial class BaseEntity : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                if ((this.IdField.Equals(value) != true))
                {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class City : ServiceReference2.BaseEntity
    {
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NameField, value) != true))
                {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lesson", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Lesson : ServiceReference2.BaseEntity
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="People", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference2.Lecturer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference2.Student))]
    public partial class People : ServiceReference2.BaseEntity
    {
        
        private ServiceReference2.City CityField;
        
        private string FnameField;
        
        private string LnameField;
        
        private int PhoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.City City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CityField, value) != true))
                {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fname
        {
            get
            {
                return this.FnameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.FnameField, value) != true))
                {
                    this.FnameField = value;
                    this.RaisePropertyChanged("Fname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lname
        {
            get
            {
                return this.LnameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LnameField, value) != true))
                {
                    this.LnameField = value;
                    this.RaisePropertyChanged("Lname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                if ((this.PhoneField.Equals(value) != true))
                {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lecturer", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Lecturer : ServiceReference2.People
    {
        
        private string DepartmentField;
        
        private ServiceReference2.LessonList lessonListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department
        {
            get
            {
                return this.DepartmentField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true))
                {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.LessonList lessonList
        {
            get
            {
                return this.lessonListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.lessonListField, value) != true))
                {
                    this.lessonListField = value;
                    this.RaisePropertyChanged("lessonList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="LessonList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Lesson")]
    public class LessonList : System.Collections.Generic.List<ServiceReference2.Lesson>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="LecturerList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Lecturer")]
    public class LecturerList : System.Collections.Generic.List<ServiceReference2.Lecturer>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="CityList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="City")]
    public class CityList : System.Collections.Generic.List<ServiceReference2.City>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary10")]
    public partial class CompositeType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                if ((this.BoolValueField.Equals(value) != true))
                {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                if ((object.ReferenceEquals(this.StringValueField, value) != true))
                {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sum", ReplyAction="http://tempuri.org/IService1/SumResponse")]
        decimal Sum(int n1, int n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sum", ReplyAction="http://tempuri.org/IService1/SumResponse")]
        System.Threading.Tasks.Task<decimal> SumAsync(int n1, int n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudentList", ReplyAction="http://tempuri.org/IService1/GetStudentListResponse")]
        ServiceReference2.StudentList GetStudentList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudentList", ReplyAction="http://tempuri.org/IService1/GetStudentListResponse")]
        System.Threading.Tasks.Task<ServiceReference2.StudentList> GetStudentListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudentListById", ReplyAction="http://tempuri.org/IService1/GetStudentListByIdResponse")]
        ServiceReference2.StudentList GetStudentListById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudentListById", ReplyAction="http://tempuri.org/IService1/GetStudentListByIdResponse")]
        System.Threading.Tasks.Task<ServiceReference2.StudentList> GetStudentListByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudentListByName", ReplyAction="http://tempuri.org/IService1/GetStudentListByNameResponse")]
        ServiceReference2.StudentList GetStudentListByName(string firstName, string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudentListByName", ReplyAction="http://tempuri.org/IService1/GetStudentListByNameResponse")]
        System.Threading.Tasks.Task<ServiceReference2.StudentList> GetStudentListByNameAsync(string firstName, string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDeleteStudent", ReplyAction="http://tempuri.org/IService1/GetDeleteStudentResponse")]
        int GetDeleteStudent(ServiceReference2.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDeleteStudent", ReplyAction="http://tempuri.org/IService1/GetDeleteStudentResponse")]
        System.Threading.Tasks.Task<int> GetDeleteStudentAsync(ServiceReference2.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInsertStudent", ReplyAction="http://tempuri.org/IService1/GetInsertStudentResponse")]
        int GetInsertStudent(ServiceReference2.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInsertStudent", ReplyAction="http://tempuri.org/IService1/GetInsertStudentResponse")]
        System.Threading.Tasks.Task<int> GetInsertStudentAsync(ServiceReference2.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNewInsertStudent", ReplyAction="http://tempuri.org/IService1/GetNewInsertStudentResponse")]
        int GetNewInsertStudent(ServiceReference2.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNewInsertStudent", ReplyAction="http://tempuri.org/IService1/GetNewInsertStudentResponse")]
        System.Threading.Tasks.Task<int> GetNewInsertStudentAsync(ServiceReference2.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInsertLecturer", ReplyAction="http://tempuri.org/IService1/GetInsertLecturerResponse")]
        int GetInsertLecturer(ServiceReference2.Lecturer lecturer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInsertLecturer", ReplyAction="http://tempuri.org/IService1/GetInsertLecturerResponse")]
        System.Threading.Tasks.Task<int> GetInsertLecturerAsync(ServiceReference2.Lecturer lecturer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLecturertList", ReplyAction="http://tempuri.org/IService1/GetLecturertListResponse")]
        ServiceReference2.LecturerList GetLecturertList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLecturertList", ReplyAction="http://tempuri.org/IService1/GetLecturertListResponse")]
        System.Threading.Tasks.Task<ServiceReference2.LecturerList> GetLecturertListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLecturertListById", ReplyAction="http://tempuri.org/IService1/GetLecturertListByIdResponse")]
        ServiceReference2.LecturerList GetLecturertListById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLecturertListById", ReplyAction="http://tempuri.org/IService1/GetLecturertListByIdResponse")]
        System.Threading.Tasks.Task<ServiceReference2.LecturerList> GetLecturertListByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLecturertListByName", ReplyAction="http://tempuri.org/IService1/GetLecturertListByNameResponse")]
        ServiceReference2.LecturerList GetLecturertListByName(string firstName, string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLecturertListByName", ReplyAction="http://tempuri.org/IService1/GetLecturertListByNameResponse")]
        System.Threading.Tasks.Task<ServiceReference2.LecturerList> GetLecturertListByNameAsync(string firstName, string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDeleteLecturer", ReplyAction="http://tempuri.org/IService1/GetDeleteLecturerResponse")]
        int GetDeleteLecturer(ServiceReference2.Lecturer lecturer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDeleteLecturer", ReplyAction="http://tempuri.org/IService1/GetDeleteLecturerResponse")]
        System.Threading.Tasks.Task<int> GetDeleteLecturerAsync(ServiceReference2.Lecturer lecturer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCityList", ReplyAction="http://tempuri.org/IService1/GetCityListResponse")]
        ServiceReference2.CityList GetCityList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCityList", ReplyAction="http://tempuri.org/IService1/GetCityListResponse")]
        System.Threading.Tasks.Task<ServiceReference2.CityList> GetCityListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUpdateStudent", ReplyAction="http://tempuri.org/IService1/GetUpdateStudentResponse")]
        int GetUpdateStudent(ServiceReference2.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUpdateStudent", ReplyAction="http://tempuri.org/IService1/GetUpdateStudentResponse")]
        System.Threading.Tasks.Task<int> GetUpdateStudentAsync(ServiceReference2.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUpdateLecturer", ReplyAction="http://tempuri.org/IService1/GetUpdateLecturerResponse")]
        int GetUpdateLecturer(ServiceReference2.Lecturer lecturer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUpdateLecturer", ReplyAction="http://tempuri.org/IService1/GetUpdateLecturerResponse")]
        System.Threading.Tasks.Task<int> GetUpdateLecturerAsync(ServiceReference2.Lecturer lecturer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ServiceReference2.CompositeType GetDataUsingDataContract(ServiceReference2.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ServiceReference2.CompositeType> GetDataUsingDataContractAsync(ServiceReference2.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCreateDeleteByIdSql", ReplyAction="http://tempuri.org/IService1/GetCreateDeleteByIdSqlResponse")]
        int GetCreateDeleteByIdSql(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCreateDeleteByIdSql", ReplyAction="http://tempuri.org/IService1/GetCreateDeleteByIdSqlResponse")]
        System.Threading.Tasks.Task<int> GetCreateDeleteByIdSqlAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IService1Channel : ServiceReference2.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReference2.IService1>, ServiceReference2.IService1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string GetData(int value)
        {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value)
        {
            return base.Channel.GetDataAsync(value);
        }
        
        public decimal Sum(int n1, int n2)
        {
            return base.Channel.Sum(n1, n2);
        }
        
        public System.Threading.Tasks.Task<decimal> SumAsync(int n1, int n2)
        {
            return base.Channel.SumAsync(n1, n2);
        }
        
        public ServiceReference2.StudentList GetStudentList()
        {
            return base.Channel.GetStudentList();
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.StudentList> GetStudentListAsync()
        {
            return base.Channel.GetStudentListAsync();
        }
        
        public ServiceReference2.StudentList GetStudentListById(int id)
        {
            return base.Channel.GetStudentListById(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.StudentList> GetStudentListByIdAsync(int id)
        {
            return base.Channel.GetStudentListByIdAsync(id);
        }
        
        public ServiceReference2.StudentList GetStudentListByName(string firstName, string lastName)
        {
            return base.Channel.GetStudentListByName(firstName, lastName);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.StudentList> GetStudentListByNameAsync(string firstName, string lastName)
        {
            return base.Channel.GetStudentListByNameAsync(firstName, lastName);
        }
        
        public int GetDeleteStudent(ServiceReference2.Student student)
        {
            return base.Channel.GetDeleteStudent(student);
        }
        
        public System.Threading.Tasks.Task<int> GetDeleteStudentAsync(ServiceReference2.Student student)
        {
            return base.Channel.GetDeleteStudentAsync(student);
        }
        
        public int GetInsertStudent(ServiceReference2.Student student)
        {
            return base.Channel.GetInsertStudent(student);
        }
        
        public System.Threading.Tasks.Task<int> GetInsertStudentAsync(ServiceReference2.Student student)
        {
            return base.Channel.GetInsertStudentAsync(student);
        }
        
        public int GetNewInsertStudent(ServiceReference2.Student student)
        {
            return base.Channel.GetNewInsertStudent(student);
        }
        
        public System.Threading.Tasks.Task<int> GetNewInsertStudentAsync(ServiceReference2.Student student)
        {
            return base.Channel.GetNewInsertStudentAsync(student);
        }
        
        public int GetInsertLecturer(ServiceReference2.Lecturer lecturer)
        {
            return base.Channel.GetInsertLecturer(lecturer);
        }
        
        public System.Threading.Tasks.Task<int> GetInsertLecturerAsync(ServiceReference2.Lecturer lecturer)
        {
            return base.Channel.GetInsertLecturerAsync(lecturer);
        }
        
        public ServiceReference2.LecturerList GetLecturertList()
        {
            return base.Channel.GetLecturertList();
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.LecturerList> GetLecturertListAsync()
        {
            return base.Channel.GetLecturertListAsync();
        }
        
        public ServiceReference2.LecturerList GetLecturertListById(int id)
        {
            return base.Channel.GetLecturertListById(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.LecturerList> GetLecturertListByIdAsync(int id)
        {
            return base.Channel.GetLecturertListByIdAsync(id);
        }
        
        public ServiceReference2.LecturerList GetLecturertListByName(string firstName, string lastName)
        {
            return base.Channel.GetLecturertListByName(firstName, lastName);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.LecturerList> GetLecturertListByNameAsync(string firstName, string lastName)
        {
            return base.Channel.GetLecturertListByNameAsync(firstName, lastName);
        }
        
        public int GetDeleteLecturer(ServiceReference2.Lecturer lecturer)
        {
            return base.Channel.GetDeleteLecturer(lecturer);
        }
        
        public System.Threading.Tasks.Task<int> GetDeleteLecturerAsync(ServiceReference2.Lecturer lecturer)
        {
            return base.Channel.GetDeleteLecturerAsync(lecturer);
        }
        
        public ServiceReference2.CityList GetCityList()
        {
            return base.Channel.GetCityList();
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.CityList> GetCityListAsync()
        {
            return base.Channel.GetCityListAsync();
        }
        
        public int GetUpdateStudent(ServiceReference2.Student student)
        {
            return base.Channel.GetUpdateStudent(student);
        }
        
        public System.Threading.Tasks.Task<int> GetUpdateStudentAsync(ServiceReference2.Student student)
        {
            return base.Channel.GetUpdateStudentAsync(student);
        }
        
        public int GetUpdateLecturer(ServiceReference2.Lecturer lecturer)
        {
            return base.Channel.GetUpdateLecturer(lecturer);
        }
        
        public System.Threading.Tasks.Task<int> GetUpdateLecturerAsync(ServiceReference2.Lecturer lecturer)
        {
            return base.Channel.GetUpdateLecturerAsync(lecturer);
        }
        
        public ServiceReference2.CompositeType GetDataUsingDataContract(ServiceReference2.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.CompositeType> GetDataUsingDataContractAsync(ServiceReference2.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public int GetCreateDeleteByIdSql(int id)
        {
            return base.Channel.GetCreateDeleteByIdSql(id);
        }
        
        public System.Threading.Tasks.Task<int> GetCreateDeleteByIdSqlAsync(int id)
        {
            return base.Channel.GetCreateDeleteByIdSqlAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WcfServiceLibrary10/Service1/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
